# Generated by Django 5.0.2 on 2024-02-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
